# start with a basic python instance
FROM python:3

# pip to pull in Flask and some other fun stuff
COPY requirements.txt requirements.txt
RUN ["pip","install","--upgrade","pip"]
RUN ["pip","install","-r","requirements.txt"]

# start your flask app here *todo*
