FROM postgres:latest

RUN apt-get update && apt-get install -y curl

COPY cloud_sql_proxy /cloud_sql_proxy

ADD database_creation.sql /docker-entrypoint-postgres.d/

ENV DB_USER=user
ENV DB_PASS=432
ENV DB_NAME=bronze

CMD /cloud_sql_proxy -instances=<postgres-12-instance>=tcp:5432 -credential_file=/secrets/cloudsql/credentials.json &\
    PGPASSWORD=$DB_PASS psql -h 127.0.0.1 -U $DB_USER -d $DB_NAME 
