version: "3"

services:
  database:
    image: postgis/postgis:15-3.3-alpine
    container_name: postgis_database
    environment: 
      - POSTGRES_USER=postgis
      - POSTGRES_PASSWORD=432_db
      - POSTGRES_DB=default
    volumes:
      - ../db/postgis_data:/var/lib/postgresql/data
      - ../db/database_creation:/home/pgis
    networks:
      - pgis
    ports:
      - "5432:5432"
  scraper: 
    image: golang:latest
    container_name: go_scraper
    volumes: 
      - ../scraper:/home/scrape
    networks:
      - pgis


#volumes:
   #postgres:

networks:
  pgis:
    
