steps:
# Docker Build and Push all Golang images:

- name: 'golang:latest'
  entrypoint: '/bin/bash'
  args: 
    - -c
    - |
      cd ./build-permit
      go build . 
      cd ..

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/msds432-group2/go-images/build-permit:latest','./build-permit']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/msds432-group2/go-images/build-permit:latest']



- name: 'golang:latest'
  entrypoint: '/bin/bash'
  args: 
    - -c
    - |
      cd ./covid-19-daily-cases
      go build . 
      cd ..

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/msds432-group2/go-images/covid-19-daily-cases:latest','./covid-19-daily-cases']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/msds432-group2/go-images/covid-19-daily-cases:latest']



- name: 'golang:latest'
  entrypoint: '/bin/bash'
  args: 
    - -c
    - |
      cd ./covid-19-zip
      go build . 
      cd ..

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/msds432-group2/go-images/covid-19-zip:latest','./covid-19-zip']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/msds432-group2/go-images/covid-19-zip:latest']


- name: 'golang:latest'
  entrypoint: '/bin/bash'
  args: 
    - -c
    - |
      cd ./health-ind
      go build . 
      cd ..

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/msds432-group2/go-images/health-ind:latest','./health-ind']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/msds432-group2/go-images/health-ind:latest']


- name: 'golang:latest'
  entrypoint: '/bin/bash'
  args: 
    - -c
    - |
      cd ./taxi-trips
      go build . 
      cd ..

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/msds432-group2/go-images/taxi-trips:latest','./taxi-trips']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/msds432-group2/go-images/taxi-trips:latest']


- name: 'golang:latest'
  entrypoint: '/bin/bash'
  args:
      - -c
      - | 
        cd ./TNP-trips
        go build . 
        cd ..

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/msds432-group2/go-images/TNP-trips:latest','-f-','./TNP-trips']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/msds432-group2/go-images/TNP-trips:latest']


## Docker Build and Push Postgres
#- name: 'gcr.io/cloud-builders/docker'
  #args: ['build', '-t', 'gcr.io/msds432-group2/postgres-image/postgres', '.']
#- name: 'gcr.io/cloud-builders/wget'
  #args: ['
  #dir: '/workspace'
#- name: 'gcr.io/cloud-builders/docker'
  #args: ['push', 'gcr.io/msds432-group2/postgres-image/postgres']

# Deploy containers to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'cloud-run-service', 
         '--image', 'gcr.io/msds432-group2/build-permit', '--region', 'us-central1',
         '--image', 'gcr.io/msds432-group2/covid-19-daily-cases', '--region', 'us-central1',
         '--image', 'gcr.io/msds432-group2/covid-19-zip', '--region', 'us-central1',
         '--image', 'gcr.io/msds432-group2/health-ind', '--region', 'us-central1',
         '--image', 'gcr.io/msds432-group2/taxi-trips', '--region', 'us-central1',
         '--image', 'gcr.io/msds432-group2/TNP-trips', '--region', 'us-central1',
         '--add-cloudsql-instances', 'msds432-group2:us-central1:postgres-12-instance=tcp:5432', 
         '--set-env-vars', 'PGDB=bronze,PGUSER=postgres,PGPASS=432']